### ISSUE TITLE
Post Meta Tags Cause 301 redirect

### ISSUE THREAD

**Issue by ShoGinn** [chipzoller/hugo-clarity#316]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference
- [x] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

This is a rather simple problem, I even saw it was a problem on neonmirrors.net 

Here is my fix:
https://github.com/ShoGinn/hugo-clarity/commit/43e1307ddf9cd594254d97911de98cba62b76504

(more specifically) -- https://github.com/ShoGinn/hugo-clarity/blob/43e1307ddf9cd594254d97911de98cba62b76504/layouts/partials/post-meta.html#L26

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All

Here is a screenshot depicting the crawl (red shows redirect)
![Directory Tree Graph](https://user-images.githubusercontent.com/2660603/170827987-f560484f-656b-4637-9a09-dbf1f9bacbb7.svg)

**Comment by chipzoller** [comment]
@ShoGinn it would be wonderful if you would submit a PR for this project!

**Comment by rootwork** [comment]
Looks like this was fixed in #317, so closing. Thanks for the contribution & bug fixing @ShoGinn !
