### ISSUE TITLE
home page doesn't have any meta description content

### ISSUE THREAD

**Issue by oskapt** [chipzoller/hugo-clarity#34]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

When sharing the root of a site, there is nothing but the title and an image:

<img width="965" alt="Screen Shot 2020-09-10 at 07 29 20" src="https://user-images.githubusercontent.com/171292/92717881-5ef3ac80-f337-11ea-8260-220c2f9a2ab7.png">

The meta tags for `description` are empty:
```
<meta property = "og:locale" content = "en_US" />
<meta property="og:type" content="website">
<meta name="description" content="">
<meta name = "twitter:card" content = "summary" />
<meta name = "twitter:creator" content = "@adriandotgoins">
<meta name = "twitter:title" content = "" />
<meta property = "og:url" content = "https://adriandotgoins.com/" />
<meta property = "og:title" content = "" />
<meta property = "og:description" content = "" />
<meta property = "og:image" content = "https://adriandotgoins.com/images/profile-picture-250px.png" />
```

I was able to fix this with an if/then block, but that may not be the correct way:
```
{{- if .IsHome }}
<meta property="og:type" content="website">
<meta property = "og:title" content = "{{ $site }}" />
<meta name = "twitter:title" content = "{{ $site }}" />
<meta property = "og:description" content = "{{ .Site.Params.description | truncate 160 }}" />
<meta name="description" content="{{ .Site.Params.description | truncate 160 }}">
{{- else }}
<meta property = "og:description" content = "{{ $summary }}" />
<meta property = "og:title" content = "{{ $title }}" />
<meta property="og:type" content="article">
<meta name="description" content="{{ $summary }}">
<meta name = "twitter:title" content = "{{ .Title }}" />
{{- end }}
```

This allowed me to use a `description` field under `[params]` in `config.toml` that gets picked up on the home page.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Firefox 80.0

**Comment by onweru** [comment]
@oskapt,

The [template reads](https://github.com/chipzoller/hugo-clarity/blob/2fa64317259905a767ac70f80aaae15486476c7a/layouts/partials/opengraph.html#L1-L4) the `description` from a page frontmatter.  For the homepage, that would be in `content/_index.md`.

In your `content/_index.md`, set the description as follows:

#### YAML

``` yaml
---
...
description: "your description text"
...
---
```

#### TOML

``` toml
+++
...
description: "your description text"
...
+++
```

I think this approach is better than setting it in the `config.toml`. Why? because the approach applies to any page. In fact, you can use it to explicitly set the content meta tags in an article/post. If a page is not an article, its content meta tags will be empty. If it's an article, it will automatically generate it from the content.

This ought to be documented; sorry you had to improvise, my bad.

> I was able to fix this with an if/then block, but that may not be the correct way:

You don't need this conditional

```html
{{- if .IsHome }}
<meta property="og:type" content="website">
<meta property = "og:title" content = "{{ $site }}" />
<meta name = "twitter:title" content = "{{ $site }}" />
<meta property = "og:description" content = "{{ .Site.Params.description | truncate 160 }}" />
<meta name="description" content="{{ .Site.Params.description | truncate 160 }}">
{{- else }}
```

**Comment by onweru** [comment]
To avoid future queries/confusion on the same, I have applied changes accordingly.
